// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Url struct {
	ID    int32  `db:"id" json:"id"`
	Alias string `db:"alias" json:"alias"`
	Url   string `db:"url" json:"url"`
}
